-- AlterTable
ALTER TABLE `Measure` ADD COLUMN `isDeleted` TINYINT NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE `Metrics` ADD COLUMN `isDeleted` TINYINT NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE `UnitTest` ADD COLUMN `isDeleted` TINYINT NOT NULL DEFAULT 0;
